DB_USERNAME = "root"
DB_PASSWORD = "Bhavana@31"
DB_HOST = "127.0.0.1"
DB_NAME = "task_manager"
SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False